### PR TITLE
fix: adds missing dependency to resolve package

### PR DESCRIPTION
**Pull request by Ephigenia**
I’m using riteway for simple integration-testing an API. I noticed that`bin/riteway uses some dependencies which are not listed in the `package.json`. In my case the missing "resolve" package results in the following error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'resolve'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ephigenia/Development/project/node_modules/riteway/bin/riteway:5:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

It might be that for some other projects also other dependencies used in the `bin/riteway` file are missing as they are not automatically included in their other package’s dependencies such as: "minimist", "glob" and "dotignore". Maybe it makes sense to add them to the `package.json` too.

### CODE REVIEW

**Comment by ericelliott** [comment]
It probably does make sense to explicitly require all of these. Can you add them to this PR?

**Comment by Ephigenia** [comment]
Allright, I’ve also added minimist, glob and dotignore

**Comment by Ephigenia** [comment]
@ericelliott somehow travis-ci doesn’t suceed. I can’t check why. Maybe you find time to have a look?

**Comment by ericelliott** [comment]
It looks like Travis-CI no longer has unlimited OSS builds. It was failing because we were out of credits.

**Pull request closed without merging**
