### PR TITLE
Update README with esm package

### PR DESCRIPTION
**Pull request by 3dos**
Add the usage of esm as a possible solution for esm import statements. Also made all the code snippets more consistent with corresponding language.

I'm not especially sure about the `js` language for the functions signatures though.

### CODE REVIEW

**Comment by ericelliott** [comment]
The esm option won't be an adequate babel replacement if you're also using JSX.

**Comment by 3dos** [comment]
Sure because JSX needs to be transpiled into JS. Would it make sense to make this addition to the doc clearer or do you think it shouldn't be added at all?

**Comment by ericelliott** [comment]
I think it's OK to add it, but mention that if you're using React, you'll need to use Babel instead, to compile the JSX.

**Comment by 3dos** [comment]
Hi Eric,

I hope I got it right this time. I didn't mention React but only JSX, I think this is clear enough.

**Pull request merged**
