### PR TITLE
feat: add .skip() and .only()

### PR DESCRIPTION
**Pull request by warrenv**
This PR exposes tape's .only() and .skip() methods on riteway's describe().

### CODE REVIEW

**Comment by ericelliott** [comment]
Perhaps this needs a dedicated test file to test the functionality? Fail in the tests that are not supposed to run?

**Comment by warrenv** [comment]
I did have that originally but it felt like it was testing tape (which already has tests).
I can take another shot at if it would be helpful.

**Comment by ericelliott** [comment]
Yeah, what we're testing here is not tape, but that we properly exposed the API in RITEway.

**Comment by warrenv** [comment]
ok. I'll add some tests.

**Comment by ericelliott** [comment]
Please resolve conflicts.

**Comment by ericelliott** [comment]
This broke TypeScript. See #25

**Comment by warrenv** [comment]
Yes, sorry... I noticed that afterwards. I have no clue how to do the type signature.

**Pull request merged**
